name: Has Permission
description: Check user's permission to access repository
inputs:
  username:
    required: false
    description: 'username (Default: github.actor)'
  required-permission:
    description: Required permission level (read, write, admin)
    required: true
    default: write
outputs:
  has-permission:
    description: Result of permission check
runs:
  using: node12
  main: bin/index.js
